### ISSUE TITLE
default olarak GPLv3 mü gelse :smile: 

### ISSUE THREAD

**Issue by adiloztaser** [aligoren/wp-license-me#1]
birde http://ozgurlisanslar.org.tr/ sayesinde Türkçe olarak linkler eklenebilir 

temelde güzel bir uygulama düşünelim bakalım daha nasıl geliştirebiliriz

**Comment by aligoren** [comment]
bu eklenti mi GPLv3 olmalı? Eğer onu diyorsan hemen değiştireyim :laughing:

**Comment by aligoren** [comment]
@oztaser ayrıca o türkçelerini de ekleyeyim. yardımınla hallederiz onu :laughing:

**Comment by oztaser** [comment]
eklenen postlara default olarak gplv3 gelsin.

sorduğun soruylada güzel bir eksiğimi gösterdin. public domain direk olarak halka ait olduğunu gösterir ancak yaptığın şeyin hayat boyunca özgür olmasını sağlar mı bilemedim incelemek lazım.

**Comment by aligoren** [comment]
@oztaser hallederiz o zaman? sen de biraz bakarsın. iki dil işini. functions dosyası zaten bad practice vaziyette.

**Comment by oztaser** [comment]
dün gece yazacaktım da yazamadım :unamused: finalleri bi halledelim yaparız.

**Comment by aligoren** [comment]
@oztaser Hatta renk seçimi yaptırabiliriz. Onu da wp_options'a ekleriz?

Şu facebook mavisi falan olur ya da o tarz bootstrap falan gibi renkler ekleriz bir de varsayılan renksiz de gelebilir?

**Comment by MertcanGokgoz** [comment]
@oztaser @aligoren Finaller bittikten sonra bi bakalım, wordpress plugins kısmına yüklenmesi gereken efsane bir eklenti bence

**Comment by aligoren** [comment]
@MertcanGokgoz panpa o zaman şu functions kısmını da biraz düzenleriz? Orası nasıl iyi olabilir ki?
